framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    handle_all_throwables: true
    php_errors: { log: true }
    session: { enabled: false }
    router:
        utf8: true
        resource: '%kernel.project_dir%/config/routes.yaml'
