export default {
  title: 'Construire ProTask avec AdonisJS',
  framework: 'AdonisJS 6',
  prerequisites: ['Node.js v24+', 'pnpm', 'Bases de TypeScript', 'Notions HTTP'],
  lessons: [
    {
      id: '01-start',
      title: 'Démarrer un projet AdonisJS',
      durationMinutes: 15,
      summary: 'Installer AdonisJS, créer le projet, comprendre la structure des dossiers et lancer le serveur de dev.',
      file: 'protask/guides/adonis/lessons/01-start.md',
      files: ['package.json', 'tsconfig.json', 'adonisrc.js', 'env.ts', '.env', 'config/app.ts', 'config/database.ts', 'config/bodyparser.ts', 'config/cors.ts', 'start/kernel.ts', 'bin/server.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/01-start/',
      testCategories: [],
      quiz: [
        { question: 'Quel outil AdonisJS gère les dépendances et l\'environnement ?', choices: ['Node.js', 'AdonisJS Core', 'IoC Container', 'pnpm'], answer: 2, explanation: 'AdonisJS utilise un conteneur IoC (Inversion of Control) pour résoudre les dépendances automatiquement.' },
        { question: 'Où sont définies les routes dans un projet AdonisJS ?', choices: ['app/controllers/', 'config/routes.ts', 'start/routes.ts', 'bin/server.ts'], answer: 2, explanation: 'Les routes sont définies dans start/routes.ts selon la convention AdonisJS.' },
      ],
    },
    {
      id: '02-first-server',
      title: 'Créer un premier serveur et une route publique',
      durationMinutes: 15,
      summary: 'Ajouter une route de santé et une première route publique, comprendre la différence entre route et contrôleur.',
      file: 'protask/guides/adonis/lessons/02-first-server.md',
      files: ['start/routes.ts', 'app/controllers/AuthController.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/02-first-server/',
      testCategories: [],
      quiz: [
        { question: 'Quelle est la différence entre une route et un contrôleur ?', choices: ['Une route définit l\'URL, un contrôleur contient la logique', 'Un contrôleur définit l\'URL, une route contient la logique', 'C\'est la même chose', 'Les contrôleurs sont optionnels'], answer: 0, explanation: 'La route associe une méthode HTTP et un chemin à un contrôleur qui exécute la logique métier.' },
        { question: 'Comment AdonisJS gère-t-il le corps des requêtes HTTP ?', choices: ['Via bodyparser middleware', 'Via le contrôleur directement', 'Avec fetch()', 'Avec une librairie externe'], answer: 0, explanation: 'Le bodyparser middleware est enregistré dans start/kernel.ts et parse automatiquement le corps des requêtes.' },
      ],
    },
    {
      id: '03-authentication',
      title: 'Créer une connexion utile',
      durationMinutes: 20,
      summary: 'Implémenter l\'inscription, la connexion et la déconnexion avec validation et tokens simulés.',
      file: 'protask/guides/adonis/lessons/03-authentication.md',
      files: ['start/routes.ts', 'app/controllers/AuthController.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/03-authentication/',
      testCategories: ['Authentification'],
      quiz: [
        { question: 'Pourquoi renvoyer un token après la connexion ?', choices: ['Pour identifier les requêtes suivantes', 'Pour chiffrer SQLite', 'Pour démarrer le serveur'], answer: 0, explanation: 'Le client présente ce token aux routes protégées dans l\'en-tête Authorization.' },
        { question: 'Pourquoi valider les champs dans le contrôleur plutôt que dans la route ?', choices: ['C\'est plus rapide', 'Le contrôleur centralise la logique métier', 'Les routes ne peuvent pas valider', 'AdonisJS l\'impose'], answer: 1, explanation: 'La validation fait partie de la logique métier ; le contrôleur est le bon endroit pour centraliser cette logique.' },
      ],
    },
    {
      id: '04-persistence',
      title: 'Persister les données avec SQLite et Lucid',
      durationMinutes: 25,
      summary: 'Configurer SQLite, créer une migration et un modèle User avec Lucid ORM.',
      file: 'protask/guides/adonis/lessons/04-persistence.md',
      files: ['config/database.ts', 'database/migrations/1725000000000_create_users.ts', 'app/models/User.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/04-persistence/',
      testCategories: ['Authentification'],
      quiz: [
        { question: 'Quel est le rôle d\'une migration dans Lucid ?', choices: ['Créer des modèles', 'Versionner le schéma de la base de données', 'Ajouter des données', 'Configurer SQLite'], answer: 1, explanation: 'Les migrations permettent de versionner et partager les changements de schéma de base de données entre développeurs.' },
        { question: 'Un modèle Lucid correspond à quoi dans la base ?', choices: ['Une ligne', 'Une table', 'Une colonne', 'Une requête'], answer: 1, explanation: 'Chaque modèle Lucid représente une table de la base de données et ses instances correspondent à des lignes.' },
      ],
    },
    {
      id: '05-current-user',
      title: 'Protéger les routes avec un middleware',
      durationMinutes: 20,
      summary: 'Créer un middleware d\'authentification simulé, protéger les routes et exposer l\'utilisateur connecté.',
      file: 'protask/guides/adonis/lessons/05-current-user.md',
      files: ['app/middleware/MockAuthMiddleware.ts', 'start/routes.ts', 'app/controllers/UsersController.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/05-current-user/',
      testCategories: ['Authentification'],
      quiz: [
        { question: 'Quand un middleware s\'exécute-t-il dans le cycle d\'une requête ?', choices: ['Après le contrôleur', 'Avant le contrôleur', 'Pendant le rendu', 'Après la réponse'], answer: 1, explanation: 'Un middleware s\'exécute avant le contrôleur pour filtrer ou préparer la requête.' },
        { question: 'Pourquoi utiliser un header Bearer token plutôt qu\'un cookie ?', choices: ['C\'est plus sécurisé pour une API', 'Les cookies ne fonctionnent pas', 'AdonisJS ne supporte que les tokens', 'Pour des raisons de performance'], answer: 0, explanation: 'Le header Authorization est le standard REST pour les APIs stateless, sans cookie de session.' },
      ],
    },
    {
      id: '06-boards',
      title: 'CRUD des boards avec authentification',
      durationMinutes: 25,
      summary: 'Implémenter le CRUD complet des boards, avec vérification d\'appartenance et propriétaire.',
      file: 'protask/guides/adonis/lessons/06-boards.md',
      files: ['app/models/Board.ts', 'app/models/ProjectColumn.ts', 'app/controllers/BoardsController.ts', 'start/routes.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/06-boards/',
      testCategories: ['Authentification', 'Boards'],
      quiz: [
        { question: 'Pourquoi un board a-t-il un owner et des memberIds ?', choices: ['Pour limiter le nombre d\'utilisateurs', 'Pour gérer les permissions d\'accès', 'Pour des raisons de performance', 'Pour le tri'], answer: 1, explanation: 'Le owner possède le board et les members y sont invités ; cela permet de contrôler qui peut voir ou modifier un board.' },
        { question: 'Pourquoi créer trois colonnes par défaut à la création d\'un board ?', choices: ['Pour respecter la méthode Kanban', 'C\'est une convention ProTask', 'AdonisJS l\'impose', 'Pour remplir la base'], answer: 1, explanation: 'L\'API ProTask crée Backlog, En cours et Terminé automatiquement pour que le board soit utilisable immédiatement.' },
      ],
    },
    {
      id: '07-kanban-core',
      title: 'Colonnes et cartes, le cœur du Kanban',
      durationMinutes: 30,
      summary: 'CRUD des colonnes et des cartes, avec réordonnancement et déplacement entre colonnes.',
      file: 'protask/guides/adonis/lessons/07-kanban-core.md',
      files: ['app/models/Card.ts', 'app/controllers/ColumnsController.ts', 'app/controllers/CardsController.ts', 'start/routes.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/07-kanban-core/',
      testCategories: ['Authentification', 'Boards', 'Colonnes', 'Cartes'],
      quiz: [
        { question: 'Pourquoi les routes reorder et move doivent-elles être déclarées avant :id ?', choices: ['Par convention', 'Pour éviter que :id intercepte "reorder"', 'Pour des raisons de performance', 'Ce n\'est pas nécessaire'], answer: 1, explanation: 'AdonisJS évalue les routes dans l\'ordre ; :id capturerait "reorder" comme un id. Les routes spécifiques passent avant.' },
        { question: 'Quel champ permet d\'ordonner les cartes dans une colonne ?', choices: ['id', 'order', 'position', 'rank'], answer: 1, explanation: 'Le champ order (stocké en colonne order_column) détermine la position de chaque carte dans sa colonne.' },
      ],
    },
    {
      id: '08-collaboration',
      title: 'Labels, commentaires et invitations',
      durationMinutes: 30,
      summary: 'Ajouter les labels, les commentaires et le système d\'invitation entre utilisateurs.',
      file: 'protask/guides/adonis/lessons/08-collaboration.md',
      files: ['app/models/Label.ts', 'app/models/Comment.ts', 'app/models/Invitation.ts', 'app/controllers/LabelsController.ts', 'app/controllers/CommentsController.ts', 'app/controllers/InvitationsController.ts', 'start/routes.ts'],
      checkpoint: 'protask/guides/adonis/checkpoints/08-collaboration/',
      testCategories: ['Authentification', 'Boards', 'Colonnes', 'Cartes', 'Labels', 'Commentaires', 'Invitations'],
      quiz: [
        { question: 'Pourquoi un commentaire est-il lié à une carte et non à un board ?', choices: ['Pour réduire le nombre de tables', 'Chaque commentaire concerne une carte spécifique', 'Les boards n\'ont pas de commentaires', 'Pour des raisons de performance'], answer: 1, explanation: 'Un commentaire appartient à une carte spécifique ; c\'est le principe de granularité des données.' },
        { question: 'Pourquoi une invitation doit-elle être acceptée avant d\'ajouter aux members ?', choices: ['Pour éviter les spams', 'AdonisJS l\'impose', 'Pour des raisons de sécurité', 'Pour respecter le consentement'], answer: 3, explanation: 'L\'utilisateur doit accepter explicitement l\'invitation avant d\'être ajouté comme membre du board.' },
      ],
    },
    {
      id: '09-next-steps',
      title: 'Aller plus loin et modifier le code',
      durationMinutes: 20,
      summary: 'Bilan du guide, exécuter tous les tests, et réaliser une petite modification autonome.',
      file: 'protask/guides/adonis/lessons/09-next-steps.md',
      files: ['database/seeders/seed.ts', 'package.json'],
      checkpoint: 'protask/guides/adonis/checkpoints/09-next-steps/',
      testCategories: ['Authentification', 'Boards', 'Colonnes', 'Cartes', 'Labels', 'Commentaires', 'Invitations'],
      quiz: [
        { question: 'Où trouve-t-on la liste des 19 routes API de ProTask ?', choices: ['Dans les contrôleurs', 'Dans openapi.json à la racine du projet', 'Dans package.json', 'Dans config/app.ts'], answer: 1, explanation: 'Le contrat OpenAPI openapi.json liste toutes les routes, leurs paramètres et leurs réponses.' },
        { question: 'Si tu dois ajouter un champ "priority" à une carte, par où commencer ?', choices: ['Le modèle Card, la migration, puis le contrôleur', 'Directement le contrôleur', 'La route d\'abord', 'Le seed'], answer: 0, explanation: 'On modifie d\'abord le modèle et la migration pour le nouveau champ, puis le contrôleur pour l\'exposer via l\'API.' },
      ],
    },
  ],
}
